export const games = [
  {
    id: 680,
    firmId: 94,
    firmType: "JILI",
    firmCode: "JILI",
    firmName: "JILI电子",
    gameCode: "680",
    gameName: "Super Ace",
    imgGame:
      "https://upload.cxct.org/p/20240918/cx_sports/1/1016451/png/1726655092615_new.png",
    imgBigGame: "",
    gameEntryTagName: "hot",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 686,
    firmId: 94,
    firmType: "JILI",
    firmCode: "JILI",
    firmName: "JILI电子",
    gameCode: "686",
    gameName: "Charge/Buffalo",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689308476299.jpg",
    imgBigGame: "",
    gameEntryTagName: "OK_holl",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1087,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1087",
    gameName: "Super Six Baccarat",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689406799749.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1094,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1094",
    gameName: "Space Galaxy",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689407250152.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 147553.37,
    jackpotOpen: 1,
    extraParam: null,
  },
  {
    id: 2260,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "2260",
    gameName: "Burning Stars 3™",
    imgGame:
      "https://upload.cxct.org/p/20240221/cx_sports/1/1018234/png/1708494061269.png",
    imgBigGame: "",
    gameEntryTagName: "HOT",
    markCollect: false,
    thirdGameCategory: "7",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 2833,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "2833",
    gameName: "Roulette",
    imgGame:
      "https://upload.cxct.org/p/20240909/cx_sports/1/1020351/png/1725863528154.png",
    imgBigGame: null,
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "8",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 2834,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "2834",
    gameName: "Single Hand Blackjack",
    imgGame:
      "https://upload.cxct.org/p/20240909/cx_sports/1/1018234/png/1725868603539.png",
    imgBigGame: null,
    gameEntryTagName: "HOT",
    markCollect: false,
    thirdGameCategory: "8",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 678,
    firmId: 94,
    firmType: "JILI",
    firmCode: "JILI",
    firmName: "JILI电子",
    gameCode: "678",
    gameName: "Fortune/Gems",
    imgGame:
      "https://upload.cxct.org/p/20240523/cx_sports/1/1020351/png/1716442804366.png",
    imgBigGame: "",
    gameEntryTagName: "OK_holl",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1680,
    firmId: 202,
    firmType: "EVO",
    firmCode: "EvoLive",
    firmName: "EvolutionLIVECASINO",
    gameCode: "1680",
    gameName: "Blackjack Grand VIP DNT",
    imgGame:
      "https://upload.cxct.org/p/20230719/cx_sports/1/1020351/jpg/1689748078139.jpg",
    imgBigGame: "",
    gameEntryTagName: "HOT",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_LIVE",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 662,
    firmId: 94,
    firmType: "JILI",
    firmCode: "JILI",
    firmName: "JILI电子",
    gameCode: "662",
    gameName: "Mines",
    imgGame:
      "https://upload.cxct.org/p/20240523/cx_sports/1/1020351/png/1716442911800.png",
    imgBigGame: "",
    gameEntryTagName: "HOT",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 2432,
    firmId: 221,
    firmType: "CGLIVE_S",
    firmCode: "CGLIVE_S",
    firmName: "ON Casino",
    gameCode: "2432",
    gameName: "ceshi/jili",
    imgGame:
      "https://upload.cxct.org/p/20240527/cx_sports/1/1019591/jpeg/1716792546587.jpeg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_LIVE",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 681,
    firmId: 94,
    firmType: "JILI",
    firmCode: "JILI",
    firmName: "JILI电子",
    gameCode: "681",
    gameName: "Golden Empire",
    imgGame:
      "https://upload.cxct.org/p/20240523/cx_sports/1/1020351/png/1716442961674.png",
    imgBigGame: "",
    gameEntryTagName: "OK_holl",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1681,
    firmId: 202,
    firmType: "EVO",
    firmCode: "EvoLive",
    firmName: "EvolutionLIVECASINO",
    gameCode: "1681",
    gameName: "Free Bet Blackjack",
    imgGame:
      "https://upload.cxct.org/p/20230719/cx_sports/1/1020351/jpg/1689748040605.jpg",
    imgBigGame: "",
    gameEntryTagName: "HOT",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_LIVE",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 709,
    firmId: 94,
    firmType: "JILI",
    firmCode: "JILI",
    firmName: "JILI电子",
    gameCode: "709",
    gameName: "iRich Bingo",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689310404726.jpg",
    imgBigGame: "",
    gameEntryTagName: "OK_holl",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 2248,
    firmId: 211,
    firmType: "PS",
    firmCode: "PS",
    firmName: "PlayStar Gaming",
    gameCode: "2248",
    gameName: "LUCKY ACE",
    imgGame:
      "https://upload.cxct.org/p/20240523/cx_sports/1/1020351/png/1716443089707.png",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1112,
    firmId: 91,
    firmType: "PG",
    firmCode: "PG",
    firmName: "PG",
    gameCode: "1112",
    gameName: "Lucky Neko",
    imgGame:
      "https://upload.cxct.org/p/20240523/cx_sports/1/1020351/png/1716443136960.png",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1110,
    firmId: 91,
    firmType: "PG",
    firmCode: "PG",
    firmName: "PG",
    gameCode: "1110",
    gameName: "Treasures of Aztec",
    imgGame:
      "https://upload.cxct.org/p/20230718/cx_sports/1/1020351/jpg/1689653974291.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1159,
    firmId: 91,
    firmType: "PG",
    firmCode: "PG",
    firmName: "PG",
    gameCode: "1159",
    gameName: "Journey to the Wealth",
    imgGame:
      "https://upload.cxct.org/p/20230718/cx_sports/1/1020351/jpg/1689658427708.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 2205,
    firmId: 212,
    firmType: "FC",
    firmCode: "FC",
    firmName: "FC Gaming",
    gameCode: "2205",
    gameName: "SUGAR BANG BANG",
    imgGame:
      "https://upload.cxct.org/p/20240523/cx_sports/1/1020351/png/1716443192997.png",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 682,
    firmId: 94,
    firmType: "JILI",
    firmCode: "JILI",
    firmName: "JILI电子",
    gameCode: "682",
    gameName: "Money Coming",
    imgGame:
      "https://upload.cxct.org/p/20240523/cx_sports/1/1020351/png/1716443244097.png",
    imgBigGame: "",
    gameEntryTagName: "OK_holl",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 676,
    firmId: 94,
    firmType: "JILI",
    firmCode: "JILI",
    firmName: "JILI电子",
    gameCode: "676",
    gameName: "Boxing King",
    imgGame:
      "https://upload.cxct.org/p/20240523/cx_sports/1/1020351/png/1716443276173.png",
    imgBigGame: "",
    gameEntryTagName: "OK_holl",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 684,
    firmId: 94,
    firmType: "JILI",
    firmCode: "JILI",
    firmName: "JILI电子",
    gameCode: "684",
    gameName: "Mega Ace",
    imgGame:
      "https://upload.cxct.org/p/20240523/cx_sports/1/1020351/png/1716443592054.png",
    imgBigGame: "",
    gameEntryTagName: "OK_holl",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1055,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1055",
    gameName: "Virtual Dragon Bonus Baccarat",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689316226051.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1109,
    firmId: 91,
    firmType: "PG",
    firmCode: "PG",
    firmName: "PG",
    gameCode: "1109",
    gameName: "Mahjong Ways 2",
    imgGame:
      "https://upload.cxct.org/p/20230718/cx_sports/1/1020351/jpg/1689653828330.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1115,
    firmId: 91,
    firmType: "PG",
    firmCode: "PG",
    firmName: "PG",
    gameCode: "1115",
    gameName: "Wild Bandito",
    imgGame:
      "https://upload.cxct.org/p/20230718/cx_sports/1/1020351/jpg/1689654378952.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1814,
    firmId: 14,
    firmType: "CQ9",
    firmCode: "SLOT",
    firmName: "CQ9 Gaming",
    gameCode: "1814",
    gameName: "Money Tree",
    imgGame:
      "https://upload.cxct.org/p/20230726/cx_sports/1/1021027/jpg/1690356664600.jpg",
    imgBigGame: "",
    gameEntryTagName: "hot",
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 2749,
    firmId: 14,
    firmType: "CQ9",
    firmCode: "SLOT",
    firmName: "CQ9 Gaming",
    gameCode: "2749",
    gameName: "Lucky Fishing",
    imgGame:
      "https://upload.cxct.org/p/20240730/cx_sports/1/1020351/jpg/1722311263263.jpg",
    imgBigGame: null,
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 2444,
    firmId: 111,
    firmType: "AP",
    firmCode: "AP",
    firmName: "OKSLOTS",
    gameCode: "2444",
    gameName: "Dragon Chi's Quest",
    imgGame:
      "https://upload.cxct.org/p/20240613/cx_sports/1/1020351/png/1718273932818.png",
    imgBigGame: null,
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 2750,
    firmId: 14,
    firmType: "CQ9",
    firmCode: "SLOT",
    firmName: "CQ9 Gaming",
    gameCode: "2750",
    gameName: "Hot Spin",
    imgGame:
      "https://upload.cxct.org/p/20240730/cx_sports/1/1020351/jpg/1722311391301.jpg",
    imgBigGame: null,
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 743,
    firmId: 111,
    firmType: "AP",
    firmCode: "AP",
    firmName: "OKSLOTS",
    gameCode: "743",
    gameName: "Xiang Qi Ways",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689304052426.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 2751,
    firmId: 14,
    firmType: "CQ9",
    firmCode: "SLOT",
    firmName: "CQ9 Gaming",
    gameCode: "2751",
    gameName: "Paradise",
    imgGame:
      "https://upload.cxct.org/p/20240730/cx_sports/1/1020351/jpg/1722311435618.jpg",
    imgBigGame: null,
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 663,
    firmId: 94,
    firmType: "JILI",
    firmCode: "JILI",
    firmName: "JILI电子",
    gameCode: "663",
    gameName: "Go Rush",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689309228222.jpg",
    imgBigGame: "",
    gameEntryTagName: "HOT",
    markCollect: false,
    thirdGameCategory: "",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 2752,
    firmId: 14,
    firmType: "CQ9",
    firmCode: "SLOT",
    firmName: "CQ9 Gaming",
    gameCode: "2752",
    gameName: "World Cup Russia 2018",
    imgGame:
      "https://upload.cxct.org/p/20240730/cx_sports/1/1020351/jpg/1722311772705.jpg",
    imgBigGame: null,
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },

  {
    id: 1,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1",
    gameName: "Andar Bahar",
    imgGame:
      "https://upload.cxct.org/p/20230718/cx_sports/1/1020670/jpeg/1689665763029.jpeg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "3",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 514,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "514",
    gameName: "888 Fortunes",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689399479811.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 719,
    firmId: 111,
    firmType: "AP",
    firmCode: "AP",
    firmName: "OKSLOTS",
    gameCode: "719",
    gameName: "3 Warlords",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689303535945.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 575,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "575",
    gameName: "Thunder Blackjack",
    imgGame:
      "https://upload.cxct.org/p/20230713/cx_sports/1/1020351/jpg/1689240403651.jpg",
    imgBigGame: "",
    gameEntryTagName: "POPULAR",
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 891,
    firmId: 92,
    firmType: "NEWPT",
    firmCode: "pt_ngm",
    firmName: "NEWPT",
    gameCode: "891",
    gameName: "Premium Blackjack",
    imgGame:
      "https://upload.cxct.org/p/20230713/cx_sports/1/1020351/jpg/1689246572243.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 557,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "557",
    gameName: "Burning Stars 3™",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689403776856.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "7",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 2430,
    firmId: 94,
    firmType: "JILI",
    firmCode: "JILI",
    firmName: "JILI",
    gameCode: "2430",
    gameName: "The Big Bopper®The Big Bopper®",
    imgGame:
      "https://upload.cxct.org/p/20240527/cx_sports/1/1019591/jpeg/1716792420825.jpeg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1102,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1102",
    gameName: "The Lost City of Gold",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689408560903.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1097,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1097",
    gameName: "Journey To The west 2",
    imgGame:
      "https://upload.cxct.org/p/20231010/cx_sports/1/1015971/jpg/1696917626970.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 37113.33,
    jackpotOpen: 1,
    extraParam: null,
  },
  {
    id: 1065,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1065",
    gameName: "KenoSoccer",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689318693294.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1056,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1056",
    gameName: "Royal Tiger Baccarat",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689316300724.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 722,
    firmId: 111,
    firmType: "AP",
    firmCode: "AP",
    firmName: "OKSLOTS",
    gameCode: "722",
    gameName: "Lucky Dragon",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689303589167.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1090,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1090",
    gameName: "SicBo",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689406955075.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1057,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1057",
    gameName: "Cash or crash",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689316397245.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1095,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1095",
    gameName: "Blooming Riches",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689407666338.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1084,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1084",
    gameName: "King of Seven",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689406599927.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 1,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 165790.89,
    jackpotOpen: 1,
    extraParam: null,
  },
  {
    id: 1101,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1101",
    gameName: "Mischievous Pirates",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689408479826.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1075,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1075",
    gameName: "Goldy Piggy",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689405755624.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1086,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1086",
    gameName: "Lucky Leprechaun",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689406733052.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 165790.89,
    jackpotOpen: 1,
    extraParam: null,
  },
  {
    id: 1062,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1062",
    gameName: "Number Game",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689318446554.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1059,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1059",
    gameName: "Basketball Strike",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689316633494.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1043,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1043",
    gameName: "Virtual SicBo",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689315244041.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1105,
    firmId: 111,
    firmType: "AP",
    firmCode: "AP",
    firmName: "OKSLOTS",
    gameCode: "1105",
    gameName: "Bunny to the Moon",
    imgGame:
      "https://upload.cxct.org/p/20230717/cx_sports/1/1020351/jpg/1689562957662.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1104,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1104",
    gameName: "Raging Bull",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689408696937.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1100,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1100",
    gameName: "Vampires Feast",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689408410102.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1060,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1060",
    gameName: "Keno",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689318311166.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1064,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1064",
    gameName: "KenoWar",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689318605180.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1066,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1066",
    gameName: "AtomWar",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689318741597.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1103,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1103",
    gameName: "Five Blessings",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689408620172.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1071,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1071",
    gameName: "Galaxy Attack",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689389550487.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1058,
    firmId: 87,
    firmType: "FKG",
    firmCode: "FKG",
    firmName: "FunkyGame",
    gameCode: "1058",
    gameName: "Speed Lotto",
    imgGame:
      "https://upload.cxct.org/p/20230714/cx_sports/1/1020351/jpg/1689316577012.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: null,
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1082,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1082",
    gameName: "Great Ocean",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689406435414.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 0,
    jackpotOpen: 0,
    extraParam: null,
  },
  {
    id: 1083,
    firmId: 88,
    firmType: "TPG",
    firmCode: "TPG",
    firmName: "TPG",
    gameCode: "1083",
    gameName: "King of Fruits",
    imgGame:
      "https://upload.cxct.org/p/20230715/cx_sports/1/1020351/jpg/1689406524930.jpg",
    imgBigGame: "",
    gameEntryTagName: null,
    markCollect: false,
    thirdGameCategory: "1",
    countPlayed: 0,
    supportTrial: 0,
    maintain: 0,
    gameType: "OK_GAMES",
    jackpotAmount: 165790.89,
    jackpotOpen: 1,
    extraParam: null,
  },
];
